/* THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD. */
/* DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */
export { GRAPHQL_PLAYGROUND_GET as GET, GRAPHQL_POST as POST } from '@payloadcms/next/routes'
