/* THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD. */
/* DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */
export {
  REST_DELETE as DELETE,
  REST_GET as GET,
  REST_OPTIONS as OPTIONS,
  REST_PATCH as PATCH,
  REST_POST as POST,
  REST_PUT as PUT,
} from '@payloadcms/next/routes'
